<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "http2_push"
 *
 * Auto generated by Extension Builder 2016-05-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'HTTP/2 Push',
	'description' => 'HTTP/2 Push for TYPO3. Be sure to include extension after scriptmerger if installed. It should be the "last hook".',
	'category' => 'misc',
	'author' => 'Kevin Lieser',
	'author_email' => 'info@ka-mediendesign.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.3.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);